-- 코드를 입력하세요
--SELECT T2.TITLE AS TITLE, T1. BOARD_ID AS BOARD_ID, T1.REPLY_ID AS REPLY_ID, 
  --      T1.WRITER_ID AS WRITER_ID, T1. CONTENTS AS CONTENTS,
    --    TO_CHAR(T1.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
   -- FROM USED_GOODS_REPLY T1 JOIN USED_GOODS_BOARD T2 ON T1.BOARD_ID = T2.BOARD_ID
   -- AND T1.CONTENTS != ''
     --   WHERE T1.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
       --     AND T1.CREATED_DATE <= TO_DATE('2022-10-31', 'YYYY-MM-DD')
         --       ORDER BY T1.CREATED_DATE, T2.TITLE;
                
SELECT T1.TITLE                               AS TITLE 
     , T1.BOARD_ID                            AS BOARD_ID
     , T2.REPLY_ID                            AS REPLY_ID
     , T2.WRITER_ID                           AS WRITER_ID 
     , T2.CONTENTS                            AS CONTENTS
     , TO_CHAR(T2.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
  FROM USED_GOODS_BOARD       T1
  JOIN USED_GOODS_REPLY       T2
    ON T1.BOARD_ID  = T2.BOARD_ID
   AND T2.CONTENTS != ' ' 
 WHERE T1.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
   AND T1.CREATED_DATE <= TO_DATE('2022-10-31', 'YYYY-MM-DD')
 ORDER BY T2.CREATED_DATE ASC
        , T1.TITLE        ASC ;